# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("sigfit_ext_emu", "sigfit_ext_nmf", "sigfit_fit_emu", "sigfit_fit_nmf", "sigfit_fit_nmf_hier2", "sigfit_fitex_emu", "sigfit_fitex_nmf")

# load each stan module
Rcpp::loadModule("stan_fit4sigfit_ext_emu_mod", what = TRUE)
Rcpp::loadModule("stan_fit4sigfit_ext_nmf_mod", what = TRUE)
Rcpp::loadModule("stan_fit4sigfit_fit_emu_mod", what = TRUE)
Rcpp::loadModule("stan_fit4sigfit_fit_nmf_mod", what = TRUE)
Rcpp::loadModule("stan_fit4sigfit_fit_nmf_hier2_mod", what = TRUE)
Rcpp::loadModule("stan_fit4sigfit_fitex_emu_mod", what = TRUE)
Rcpp::loadModule("stan_fit4sigfit_fitex_nmf_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
